{% set gitchannel = "MSeifert04" %}
{% set name = "iteration_utilities" %}
{% set version = "0.0.11" %}
{% set sha256 = "f9dccd98f2785ca9914b39ff1267c4073d0dc3869c592024ebe8b7d0602e2f71" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  features:
  - vc9  # [win and py27]
  - vc10  # [win and py34]
  - vc14  # [win and py35]
  skip: True  # [osx]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - pytest-runner
  run:
    - python

test:
  requires:
    - pytest
  imports:
    - iteration_utilities
  commands:
    - git clone https://github.com/{{ gitchannel }}/{{ name }}.git
    - cd {{ name }}
    - git checkout tags/v{{ version }}
    - py.test tests

about:
  home: https://github.com/MSeifert04/iteration_utilities
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.rst
  summary: 'Itertools recipes for Python 2/3 and more.'
  doc_url: http://iteration-utilities.rtfd.io
  dev_url: https://github.com/MSeifert04/iteration_utilities

extra:
  recipe-maintainers:
    - MSeifert04
